import { IMAGES } from "./images";

export const PATHWAY_LIST = [
  { slug: "new-to-faith", title: "I'm New to Faith", icon: "✦" },
  { slug: "grow-closer", title: "I Want to Grow Closer to God", icon: "🔥" },
  { slug: "peace", title: "I Need Peace", icon: "🕊" },
  { slug: "healing", title: "I Need Healing", icon: "💧" },
  { slug: "direction", title: "I Need Direction", icon: "🧭" },
  { slug: "spiritual-attack", title: "I'm Under Spiritual Attack", icon: "⚔" },
];

export const PATHWAY_DETAILS = {
  "new-to-faith": {
    title: "I'm New to Faith",
    image: IMAGES.newToFaith,
    encouragement: "Welcome. This is the most important step you'll ever take. God has been drawing you to Himself, and today He meets you right where you are. You don't need to have it all figured out — you just need to say yes.",
    scripture: '"For God so loved the world that He gave His one and only Son, that whoever believes in Him shall not perish but have eternal life." — John 3:16',
    prayer: "Lord Jesus, I come to You just as I am. I believe You are the Son of God and that You died for me and rose again. I ask You to forgive my sins, come into my heart, and be the Lord of my life. Fill me with Your Holy Spirit and guide my every step. I give my life to You today. In Jesus' name, Amen.",
    declaration: "I am a new creation in Christ. The old has gone, the new has come. I am forgiven, I am loved, and I belong to God. My life has purpose, and the Holy Spirit is my guide.",
    nextStep: "Start reading the book of John in the Bible. Take it one chapter at a time. Ask God to open your eyes as you read. He will speak to you.",
  },
  "grow-closer": {
    title: "I Want to Grow Closer to God",
    image: IMAGES.growCloser,
    encouragement: "The desire to grow closer to God is itself a sign that He is drawing you deeper. He rewards those who earnestly seek Him. Press in — there is more of His presence, more of His voice, and more of His power waiting for you.",
    scripture: '"Draw near to God, and He will draw near to you." — James 4:8',
    prayer: "Father, I hunger for more of You. I don't want to stay where I am — I want to go deeper. Remove anything in my life that holds me back from Your presence. Open my eyes to see You more clearly, my ears to hear Your voice, and my heart to receive all that You have for me. In Jesus' name, Amen.",
    declaration: "I am pressing into the deeper things of God. I am not staying on the surface. The Holy Spirit is leading me into greater intimacy, revelation, and power. I will know God more.",
    nextStep: "Set aside 15 minutes each morning to sit in God's presence. Don't rush to speak — just listen. Worship. Let Him fill you.",
  },
  "peace": {
    title: "I Need Peace",
    image: IMAGES.peace,
    encouragement: "The peace of God is not the absence of trouble — it is the presence of God in the middle of trouble. He is your refuge and your calm. Whatever storm you're facing, His peace is available to you right now.",
    scripture: '"Peace I leave with you; my peace I give you. I do not give to you as the world gives. Do not let your hearts be troubled and do not be afraid." — John 14:27',
    prayer: "Lord, I bring every anxious thought, every worry, and every fear to You right now. I lay them at Your feet. I ask for Your supernatural peace to flood my heart and mind. Guard me with a peace that goes beyond what I can understand. I trust You. In Jesus' name, Amen.",
    declaration: "I have the peace of God that surpasses all understanding. My mind is guarded, my heart is at rest, and my spirit is anchored in Christ. I will not be shaken.",
    nextStep: "Write down what's troubling you, then write Philippians 4:6-7 beside it. Pray over it. Release it to God.",
  },
  "healing": {
    title: "I Need Healing",
    image: IMAGES.healing,
    encouragement: "God is your healer. He is Jehovah Rapha — the God who heals. Whether you need healing in your body, your mind, your emotions, or your relationships, nothing is too hard for Him. Reach out in faith today.",
    scripture: '"He was pierced for our transgressions, He was crushed for our iniquities; the punishment that brought us peace was on Him, and by His wounds we are healed." — Isaiah 53:5',
    prayer: "Heavenly Father, I come to You as the Great Physician. You know every pain, every wound, every broken place in my life. I ask for Your healing power to touch me right now — body, soul, and spirit. I receive Your restoration by faith. Let Your healing flow through me. In Jesus' name, Amen.",
    declaration: "By the stripes of Jesus, I am healed. Sickness, pain, and brokenness have no authority over my life. I am restored, renewed, and made whole in the name of Jesus.",
    nextStep: "Speak Isaiah 53:5 over yourself every morning and night. Lay hands on the area that needs healing and declare that God is restoring you.",
  },
  "direction": {
    title: "I Need Direction",
    image: IMAGES.pathways,
    encouragement: "God is not a God of confusion — He is a God of order, clarity, and purpose. If you feel lost or uncertain, know that He has already prepared the path. He promises to guide you when you trust Him with all your heart.",
    scripture: '"Trust in the Lord with all your heart and lean not on your own understanding; in all your ways submit to Him, and He will make your paths straight." — Proverbs 3:5-6',
    prayer: "Father, I feel uncertain about the way ahead. I don't know which way to go, but You do. I surrender my plans and my confusion to You. Speak clearly to my heart. Order my steps. Lead me on the path of Your will and purpose. In Jesus' name, Amen.",
    declaration: "God is directing my steps. I am not lost and I am not alone. The Holy Spirit is my guide, and He is making my path clear. I walk in divine purpose and heavenly direction.",
    nextStep: "Write down the decision you're facing. Fast and pray for one day. Ask God to confirm His direction through His Word, through peace, and through trusted counsel.",
  },
  "spiritual-attack": {
    title: "I'm Under Spiritual Attack",
    image: IMAGES.pathways,
    encouragement: "If the enemy is attacking you, it's because you're a threat to his kingdom. You are not defenceless — you are armed with the full armour of God and the name of Jesus. Stand firm. The battle belongs to the Lord.",
    scripture: '"Submit yourselves, then, to God. Resist the devil, and he will flee from you." — James 4:7',
    prayer: "Father, I take my stand in the authority of Jesus Christ. I put on the full armour of God. I resist every attack of the enemy — every lie, every fear, every oppression — and I command it to flee in Jesus' name. Cover me with Your blood. Surround me with Your angels. Fight for me, Lord. In Jesus' mighty name, Amen.",
    declaration: "No weapon formed against me shall prosper. I am covered by the blood of Jesus. Greater is He who is in me than he who is in the world. I stand in victory. The enemy is defeated.",
    nextStep: "Read Ephesians 6:10-18 and speak each piece of God's armour over yourself. Worship out loud — it is a weapon of warfare.",
  },
};

export const DAILY_DEVOTIONS = [
  {
    title: "Step Into His Presence",
    scripture: '"Be still, and know that I am God." — Psalm 46:10',
    encouragement: "Before you step into the demands of the day, step into His presence. God isn't distant — He's right here, waiting for you. In the stillness, His voice becomes clear. In His presence, everything shifts.",
    prayer: "Lord, I pause everything to meet with You. Quiet the noise around me and within me. I want to hear Your voice today. Fill me with Your peace and power. Let today be marked by Your presence. In Jesus' name, Amen.",
    declaration: "I carry the presence of God with me today. Wherever I go, His peace goes with me. I am led by the Spirit, and nothing can separate me from His love.",
    actionStep: "Before you start your day, sit for 5 minutes in silence. Invite the Holy Spirit to speak. Write down anything that comes to your heart.",
  },
  {
    title: "Walk in Faith, Not Fear",
    scripture: '"For God has not given us a spirit of fear, but of power and of love and of a sound mind." — 2 Timothy 1:7',
    encouragement: "Fear has no authority over a child of God. When fear speaks, faith answers. You have been given power, love, and a sound mind — three Kingdom weapons against every anxious thought.",
    prayer: "Father, I reject every spirit of fear and I receive Your power, Your love, and a sound mind. Where fear has had a foothold in my life, I take it back today. I will walk in bold faith. In Jesus' name, Amen.",
    declaration: "I am not afraid. I walk in the power of God. My mind is sound, my heart is strong, and my faith is unshakeable. I move forward in confidence.",
    actionStep: "Write down one fear that has been holding you back. Speak 2 Timothy 1:7 over it three times, then take one bold step forward today.",
  },
  {
    title: "You Are Chosen",
    scripture: '"You are a chosen people, a royal priesthood, a holy nation, God\'s special possession." — 1 Peter 2:9',
    encouragement: "You are not an accident. You are not overlooked. You have been specifically chosen by God, set apart for His purpose, and called into His royal family. Walk today knowing whose you are.",
    prayer: "Lord, thank You for choosing me. Thank You that I am Yours — royal, holy, and set apart. Help me to walk today in the fullness of my identity. I am who You say I am. In Jesus' name, Amen.",
    declaration: "I am chosen by God. I am royal priesthood. I am holy and set apart. I carry the authority of the King and I walk in my Kingdom identity today.",
    actionStep: "Look in the mirror and speak your identity out loud: 'I am chosen. I am royal. I am God's special possession.' Let it sink into your spirit.",
  },
  {
    title: "Trust His Timing",
    scripture: '"He has made everything beautiful in its time." — Ecclesiastes 3:11',
    encouragement: "If you're waiting on God, don't grow weary. His timing is perfect — never late, never early. The waiting season is not wasted. God is working behind the scenes, preparing you for what He's preparing for you.",
    prayer: "Father, I trust Your timing. Even when I can't see what You're doing, I believe You are at work. Strengthen my patience and deepen my faith as I wait on You. I know Your plans are good. In Jesus' name, Amen.",
    declaration: "God's timing is perfect. I release every rush and every frustration. What God has promised, He will bring to pass. I wait in faith and expectation.",
    actionStep: "Write down one promise you're waiting on from God. Thank Him for it as though it's already done. Praise Him in the waiting.",
  },
  {
    title: "The Fire of God",
    scripture: '"Our God is a consuming fire." — Hebrews 12:29',
    encouragement: "The fire of God doesn't just destroy — it purifies, empowers, and ignites purpose. Ask the Holy Spirit to rekindle the fire within you today. Let His fire burn away the things that don't belong and ignite the things that do.",
    prayer: "Holy Spirit, set me on fire again. Burn away every distraction, every compromise, and every lukewarm place. I want the fullness of Your fire — in my worship, my prayer, my faith, and my walk. In Jesus' name, Amen.",
    declaration: "The fire of God burns within me. I am not cold, I am not lukewarm. I am on fire for God's Kingdom. His fire purifies me, empowers me, and propels me forward.",
    actionStep: "Put on a worship song and let yourself fully enter in. Ask the Holy Spirit to reignite passion in the areas of your life that have grown cold.",
  },
  {
    title: "Speak Life",
    scripture: '"The tongue has the power of life and death, and those who love it will eat its fruit." — Proverbs 18:21',
    encouragement: "Your words carry power. What you speak over your life, your family, your health, and your future matters. Today, choose to speak what God says — life, hope, victory, and blessing.",
    prayer: "Lord, guard my mouth today. Let every word I speak be full of life, truth, and faith. Help me to align my words with Your Word. I will speak life and not death. In Jesus' name, Amen.",
    declaration: "I speak life over my family, my health, my purpose, and my future. My words are seeds of faith. What I declare in agreement with God's Word will come to pass.",
    actionStep: "Choose 3 things in your life and speak a biblical truth over each one. Write them down and declare them aloud morning and evening.",
  },
  {
    title: "Victory Is Yours",
    scripture: '"But thanks be to God! He gives us the victory through our Lord Jesus Christ." — 1 Corinthians 15:57',
    encouragement: "No matter what battle you're facing, the victory has already been won. Jesus defeated every enemy at the cross. You don't fight for victory — you fight from victory. Walk in it today.",
    prayer: "Father, I thank You that victory is mine through Jesus. I don't have to fight alone, and I don't have to be afraid of any battle. You have already won. I receive Your victory today. In Jesus' name, Amen.",
    declaration: "I am more than a conqueror through Christ who loves me. Victory is mine. The battle belongs to the Lord, and I walk in His triumph. No weapon formed against me shall prosper.",
    actionStep: "Identify one area where you've felt defeated. Declare 1 Corinthians 15:57 over it and take one step of obedience in that area today.",
  },
];