export const RESOURCE_LINKS = [
  { name: "Kingdom Mandate Ministry", url: "https://kingdommandateministry.com", desc: "Main ministry site" },
  { name: "The Bible Companion", url: "https://thebiblecompanion.online", desc: "Daily Bible reading companion" },
  { name: "Kingdom Prayer Wall", url: "https://prayer.kingdommandateministry.com", desc: "Submit and pray for requests" },
  { name: "Kingdom Fire Companion", url: "https://fire.kingdommandateministry.com", desc: "Spirit-filled fire devotions" },
  { name: "Kingdom Declarations", url: "https://declarations.kingdommandateministry.com", desc: "Speak life and truth daily" },
  { name: "Kingdom Healing Room", url: "https://healing.kingdommandateministry.com", desc: "Prayers for healing and restoration" },
  { name: "Kingdom Purpose Finder", url: "https://purpose.kingdommandateministry.com", desc: "Discover your God-given purpose" },
  { name: "Kingdom Identity", url: "https://identity.kingdommandateministry.com", desc: "Know who you are in Christ" },
  { name: "Kingdom Gift Finder", url: "https://gifts.kingdommandateministry.com", desc: "Discover your spiritual gifts" },
  { name: "Kingdom Battle Plan", url: "https://battle.kingdommandateministry.com", desc: "Spiritual warfare strategies" },
  { name: "Kingdom Grace Vault", url: "https://grace.kingdommandateministry.com", desc: "Treasures of God's grace" },
  { name: "Kingdom Revival Fire", url: "https://revival.kingdommandateministry.com", desc: "Ignite revival in your life" },
  { name: "Kingdom Family Altar", url: "https://family.kingdommandateministry.com", desc: "Family worship and devotion" },
  { name: "Kingdom Marketplace Mandate", url: "https://marketplace.kingdommandateministry.com", desc: "Faith in the workplace" },
  { name: "Kingdom Freedom", url: "https://freedom.kingdommandateministry.com", desc: "Walk in true freedom" },
  { name: "YouTube Channel", url: "https://www.youtube.com/@KingdomMandateMinistry", desc: "Watch teachings and worship" },
  { name: "Contact", url: "mailto:kingdommm.chris@gmail.com", desc: "Get in touch with us" },
  { name: "Partner / Sow", url: "https://www.paypal.com/donate/?business=kingdommm.chris%40gmail.com", desc: "Sow into the Kingdom" },
];

export const FOOTER_LINKS = [
  { name: "Main Site", url: "https://kingdommandateministry.com" },
  { name: "Bible Companion", url: "https://thebiblecompanion.online" },
  { name: "Prayer Wall", url: "https://prayer.kingdommandateministry.com" },
  { name: "Fire", url: "https://fire.kingdommandateministry.com" },
  { name: "Pathway", url: "https://pathway.kingdommandateministry.com" },
  { name: "Declarations", url: "https://declarations.kingdommandateministry.com" },
  { name: "Healing", url: "https://healing.kingdommandateministry.com" },
  { name: "Purpose", url: "https://purpose.kingdommandateministry.com" },
  { name: "Identity", url: "https://identity.kingdommandateministry.com" },
  { name: "Gifts", url: "https://gifts.kingdommandateministry.com" },
  { name: "Battle", url: "https://battle.kingdommandateministry.com" },
  { name: "Grace", url: "https://grace.kingdommandateministry.com" },
  { name: "Revival", url: "https://revival.kingdommandateministry.com" },
  { name: "Family", url: "https://family.kingdommandateministry.com" },
  { name: "Marketplace", url: "https://marketplace.kingdommandateministry.com" },
  { name: "Freedom", url: "https://freedom.kingdommandateministry.com" },
  { name: "YouTube", url: "https://www.youtube.com/@KingdomMandateMinistry" },
  { name: "Contact", url: "mailto:kingdommm.chris@gmail.com" },
  { name: "Partner / Sow", url: "https://www.paypal.com/donate/?business=kingdommm.chris%40gmail.com" },
];